name: 'LD36'
version: 0.0.1
description: An absolute bare-bones web app.
#author: Ethan T <email@example.com>
#homepage: https://www.example.com

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  dart_to_js_script_rewriter:
  cobblestone:
    git: https://github.com/specialcode/cobblestone.git
  yaml:

transformers:
- $dart2js:
    suppressWarnings: false
    terse: true
    verbose: true
    commandLineOptions: [--show-package-warnings]
    minify: true
